"""Added indicator tables

Revision ID: 0d235428e551
Revises: f00c4faa7f7a
Create Date: 2025-02-19 02:06:10.604377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d235428e551'
down_revision = 'f00c4faa7f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_effectiveness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('indicator_name', sa.String(length=10), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_profit', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol', 'indicator_name', name='unique_stock_indicator')
    )
    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('sma', sa.Float(), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol', 'date', name='unique_stock_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_values')
    op.drop_table('indicator_effectiveness')
    # ### end Alembic commands ###
