"""Add live stock price model

Revision ID: 6c38531521a4
Revises: ff6d2e264cb5
Create Date: 2025-03-16 00:12:34.303513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c38531521a4'
down_revision = 'ff6d2e264cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_stock_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol', 'date', 'time', name='unique_live_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_stock_price')
    # ### end Alembic commands ###
