"""Add Transaction and Tax models

Revision ID: 6e28e358051f
Revises: 
Create Date: 2024-10-18 01:04:34.455198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e28e358051f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove these drop table commands
    # op.drop_table('stock_prices')
    # op.drop_table('stock')
    # op.drop_table('user')

    # Add creation of transactions table
    op.create_table('transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stock_symbol', sa.String(length=10), nullable=False),
        sa.Column('transaction_type', sa.String(length=4), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price_per_share', sa.Float(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Add creation of taxes table
    op.create_table('taxes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('broker_commission', sa.Float(), nullable=False),
        sa.Column('sebon_fee', sa.Float(), nullable=False),
        sa.Column('dp_amount', sa.Float(), nullable=False),
        sa.Column('capital_gain_tax', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove these create table commands for existing tables
    # op.create_table('user', ...)
    # op.create_table('stock', ...)
    # op.create_table('stock_prices', ...)

    # Add drop table commands for new tables
    op.drop_table('taxes')
    op.drop_table('transactions')
    # ### end Alembic commands ###