"""Added table for live indicator values

Revision ID: 775b4c3172b1
Revises: 6c38531521a4
Create Date: 2025-03-16 01:11:26.716133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775b4c3172b1'
down_revision = '6c38531521a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_indicator_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol', 'date', 'time', 'indicator_name', name='unique_stock_date_time_indicator')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_indicator_value')
    # ### end Alembic commands ###
