"""change stock_id to stock_symbol in stock_price table

Revision ID: f00c4faa7f7a
Revises: eb360eb3de7f
Create Date: 2025-01-31 23:54:44.274728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00c4faa7f7a'
down_revision = 'eb360eb3de7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_symbol', sa.String(length=10), nullable=False))
        batch_op.drop_constraint('stock_price_stock_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stock', ['stock_symbol'], ['symbol'])
        batch_op.drop_column('stock_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stock_price_stock_id_fkey', 'stock', ['stock_id'], ['id'])
        batch_op.drop_column('stock_symbol')

    # ### end Alembic commands ###
