"""Added best_buy and best_sell columns to IndicatorEffectiveness

Revision ID: ff6d2e264cb5
Revises: 0d235428e551
Create Date: 2025-02-20 18:26:29.950482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6d2e264cb5'
down_revision = '0d235428e551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator_effectiveness', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_buy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('best_sell', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator_effectiveness', schema=None) as batch_op:
        batch_op.drop_column('best_sell')
        batch_op.drop_column('best_buy')

    # ### end Alembic commands ###
